// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: app/stats/config.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainTraffic *DomainTrafficConfig   `protobuf:"bytes,1,opt,name=domain_traffic,json=domainTraffic,proto3" json:"domain_traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_stats_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_stats_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetDomainTraffic() *DomainTrafficConfig {
	if x != nil {
		return x.DomainTraffic
	}
	return nil
}

type DomainTrafficConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Enabled               bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BucketIntervalSeconds uint32                 `protobuf:"varint,2,opt,name=bucket_interval_seconds,json=bucketIntervalSeconds,proto3" json:"bucket_interval_seconds,omitempty"`
	RetentionSeconds      uint32                 `protobuf:"varint,3,opt,name=retention_seconds,json=retentionSeconds,proto3" json:"retention_seconds,omitempty"`
	MaxDomains            uint32                 `protobuf:"varint,4,opt,name=max_domains,json=maxDomains,proto3" json:"max_domains,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DomainTrafficConfig) Reset() {
	*x = DomainTrafficConfig{}
	mi := &file_app_stats_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainTrafficConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainTrafficConfig) ProtoMessage() {}

func (x *DomainTrafficConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainTrafficConfig.ProtoReflect.Descriptor instead.
func (*DomainTrafficConfig) Descriptor() ([]byte, []int) {
	return file_app_stats_config_proto_rawDescGZIP(), []int{1}
}

func (x *DomainTrafficConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DomainTrafficConfig) GetBucketIntervalSeconds() uint32 {
	if x != nil {
		return x.BucketIntervalSeconds
	}
	return 0
}

func (x *DomainTrafficConfig) GetRetentionSeconds() uint32 {
	if x != nil {
		return x.RetentionSeconds
	}
	return 0
}

func (x *DomainTrafficConfig) GetMaxDomains() uint32 {
	if x != nil {
		return x.MaxDomains
	}
	return 0
}

type ChannelConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Blocking        bool                   `protobuf:"varint,1,opt,name=Blocking,proto3" json:"Blocking,omitempty"`
	SubscriberLimit int32                  `protobuf:"varint,2,opt,name=SubscriberLimit,proto3" json:"SubscriberLimit,omitempty"`
	BufferSize      int32                  `protobuf:"varint,3,opt,name=BufferSize,proto3" json:"BufferSize,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelConfig) Reset() {
	*x = ChannelConfig{}
	mi := &file_app_stats_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfig) ProtoMessage() {}

func (x *ChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfig.ProtoReflect.Descriptor instead.
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return file_app_stats_config_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelConfig) GetBlocking() bool {
	if x != nil {
		return x.Blocking
	}
	return false
}

func (x *ChannelConfig) GetSubscriberLimit() int32 {
	if x != nil {
		return x.SubscriberLimit
	}
	return 0
}

func (x *ChannelConfig) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

var File_app_stats_config_proto protoreflect.FileDescriptor

const file_app_stats_config_proto_rawDesc = "" +
	"\n" +
	"\x16app/stats/config.proto\x12\x0exray.app.stats\"T\n" +
	"\x06Config\x12J\n" +
	"\x0edomain_traffic\x18\x01 \x01(\v2#.xray.app.stats.DomainTrafficConfigR\rdomainTraffic\"\xb5\x01\n" +
	"\x13DomainTrafficConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x126\n" +
	"\x17bucket_interval_seconds\x18\x02 \x01(\rR\x15bucketIntervalSeconds\x12+\n" +
	"\x11retention_seconds\x18\x03 \x01(\rR\x10retentionSeconds\x12\x1f\n" +
	"\vmax_domains\x18\x04 \x01(\rR\n" +
	"maxDomains\"u\n" +
	"\rChannelConfig\x12\x1a\n" +
	"\bBlocking\x18\x01 \x01(\bR\bBlocking\x12(\n" +
	"\x0fSubscriberLimit\x18\x02 \x01(\x05R\x0fSubscriberLimit\x12\x1e\n" +
	"\n" +
	"BufferSize\x18\x03 \x01(\x05R\n" +
	"BufferSizeBL\n" +
	"\x12com.xray.app.statsP\x01Z#github.com/xtls/xray-core/app/stats\xaa\x02\x0eXray.App.Statsb\x06proto3"

var (
	file_app_stats_config_proto_rawDescOnce sync.Once
	file_app_stats_config_proto_rawDescData []byte
)

func file_app_stats_config_proto_rawDescGZIP() []byte {
	file_app_stats_config_proto_rawDescOnce.Do(func() {
		file_app_stats_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_stats_config_proto_rawDesc), len(file_app_stats_config_proto_rawDesc)))
	})
	return file_app_stats_config_proto_rawDescData
}

var file_app_stats_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_stats_config_proto_goTypes = []any{
	(*Config)(nil),              // 0: xray.app.stats.Config
	(*DomainTrafficConfig)(nil), // 1: xray.app.stats.DomainTrafficConfig
	(*ChannelConfig)(nil),       // 2: xray.app.stats.ChannelConfig
}
var file_app_stats_config_proto_depIdxs = []int32{
	1, // 0: xray.app.stats.Config.domain_traffic:type_name -> xray.app.stats.DomainTrafficConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_stats_config_proto_init() }
func file_app_stats_config_proto_init() {
	if File_app_stats_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_stats_config_proto_rawDesc), len(file_app_stats_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_stats_config_proto_goTypes,
		DependencyIndexes: file_app_stats_config_proto_depIdxs,
		MessageInfos:      file_app_stats_config_proto_msgTypes,
	}.Build()
	File_app_stats_config_proto = out.File
	file_app_stats_config_proto_goTypes = nil
	file_app_stats_config_proto_depIdxs = nil
}
